---
title: "week5-rexercise"
format: html
editor: visual
---

```{r}
library("readr")
library("sf")
library("terra")
library("dplyr")
library("lubridate")
library("ggplot2")
library("tmap")

wildschwein_BE <- read_delim("datasets/wildschwein_BE_2056.csv", ",") |>
    st_as_sf(coords = c("E", "N"), crs = 2056, remove = FALSE)


```

```{r}
fanel <- read_sf("datasets/Feldaufnahmen_Fanel.gpkg")

plot(fanel["Frucht"])
plot(wildschwein_BE, add = TRUE) #add to same map

ggplot(fanel) +
  geom_sf(aes(fill = Frucht))+
  geom_sf(data = wildschwein_BE, alpha = .3, pch = ".")+ #pch defines the type of visualisation shape
  theme(legend.position = "none")+
  coord_sf(datum = 2056) # gives swiss labelling of coordinates

# When adding a tlm, just visualize first, to see if the area is as expected
```

use st_join to annotate wildboar data with landuse

```{r}
wildschwein_BE_annot <- st_join(wildschwein_BE, fanel)

ggplot() +
  geom_sf(data = wildschwein_BE_annot, aes(colour = Frucht), alpha = .3) + 
  theme(legend.position = "none")+
  coord_sf(datum = 2056)


```
